### ISSUE TITLE
Control renders on lower left part of the window

### ISSUE THREAD

**Issue by di0rdna** [opentk/GLWpfControl#67] opened 2022-04-15 11:23 UTC
I am using the control with the code from the provided example and I get the following result :
![image](https://user-images.githubusercontent.com/21369509/163565139-b272841f-6b3d-4183-9d99-2849b96704d0.png)

Am I doing something wrong?

**Comment by di0rdna** [comment] 2022-04-15 15:52
This is caused by the scissor test. Any thoughts on that?

**Comment by NogginBops** [comment] 2022-04-16 00:32
Are you calling `glViewport` with the correct values?

**Comment by NogginBops** [comment] 2022-04-16 00:33
What version of the control are you using?

**Comment by paokakis** [comment] 2022-04-16 08:54
My first thought was to call the set viewport, so I did but it didn't fix the problem. Only after disabling the scissor test I got the whole view. I am not at home at the moment so I can not say the exact version of the control but I'm using the latest from nugget

**Comment by NogginBops** [comment] 2022-04-16 18:41
So this was caused by scissor testing being enabled in your application? So not an issue with GlWpfControl?

**Comment by di0rdna** [comment] 2022-04-16 22:05
I just enabled the scissor test and I had this result.

**Comment by NogginBops** [comment] 2022-04-16 22:52
Are you setting the scissor area?

**Comment by di0rdna** [comment] 2022-04-17 08:52
No

**Comment by NogginBops** [comment] 2022-04-17 13:17
Then I'm not sure how this is a GlWpfControl issue?

**Comment by paokakis** [comment] 2022-04-17 13:23
Yes it is probably opentk issue

**Comment by NogginBops** [comment] 2022-04-17 20:03
I'm not sure how it would be an opentk issue either? 
It's clearly not supposed to work from the api usage, if you are using scissor tests you should set the scissor area too.

It's not an issue with GlWpfControl or OpenTK, the issue is the OpenGL api usage.

**Comment by paokakis** [comment] 2022-04-18 07:58
Anyway you can close this issue

**Closed** 2022-04-18 18:44 UTC
Labels: needs verification
