### ISSUE TITLE
GLWpfControl.sln can not execute

### ISSUE THREAD

**Issue by nyendwa** [opentk/GLWpfControl#83] opened 2022-07-13 15:38 UTC
I downloaded GLWpfControl-master tutorial from the OpenTK repository, unfortunately, the project can not execute and it is giving me the following error below, I am using Visual Studio 2022 community version. I want to know whether the problem is unique to my machine or there is something I am not doing correctly. 

A project with an Output type of Class Library cannot be started directly. In order to debug this project, add an executable project to this solution which is references the library project. Set the executable project as the startup project.

**Comment by NogginBops** [comment] 2022-07-13 18:03
You cannot execute the GLWpfControl itself, you need to select the example projects to be able to run them.

**Comment by nyendwa** [comment] 2022-07-13 18:28
Unlike the LearnOpenTK, the interface to run the example projects looks
different. Help me run through this example.
[image: image.png]

**Comment by NogginBops** [comment] 2022-07-15 08:11
It seems like your image failed to upload

**Comment by NogginBops** [comment] 2022-07-15 13:53
This is how it looks for me when I load in the solution.
![image](https://user-images.githubusercontent.com/3778357/179237147-8576aa70-22f5-4cf9-a7ee-fcfd83b8c472.png)

**Comment by NogginBops** [comment] 2022-07-15 14:07
There might have been a problem where the startup object of the Example project was not properly set. You can do this manually by going into the project properties.
I've opened #85 to fix this.

**Comment by nyendwa** [comment] 2022-07-15 14:10
I am not sure why my examples are not loading when I load my solution. I am using Visual studio 2022. From: Julius HägerSent: Friday, July 15, 2022 3:53 PMTo: opentk/GLWpfControlCc: Janny Nyendwa; AuthorSubject: Re: [opentk/GLWpfControl] GLWpfControl.sln can not execute (Issue #83) This is how it looks for me when I load in the solution.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by NogginBops** [comment] 2022-07-21 15:51
This should be fixed with #85

**Closed by NogginBops** 2022-07-21 15:51 UTC
Labels: question

**Comment by nyendwa** [comment] 2022-10-11 07:57
Is there a way to trouble shoot the image?

**Comment by NogginBops** [comment] 2022-10-11 09:10
What does that mean? @nyendwa

**Comment by nyendwa** [comment] 2022-10-11 09:24
Not sure what your question mean because the case was closed. Someone
recommended my graphics card could be too small to handle the current
version of GLWpfControl.

**Comment by NogginBops** [comment] 2022-10-11 09:38
We can reopen this issue if you think the issue isn't resolved. Are you still not able to run the project?

**Comment by nyendwa** [comment] 2022-10-11 10:36
I think the program is fine, I need to upgrade my graphics card. What's the
minimum GPU that requires to run it?

**Comment by NogginBops** [comment] 2022-10-11 11:25
All that really is required is the `WGL_NV_DX_interop` extension to be present. 
By default the control requests a OpenGL 3.3 context but that can be changed in the settings, the example should work with all versions down to 1.0.

Though it seems like the code isn't requesting a compatibility profile which could be an issue as it's using legacy drawing operations, that are not supposed to work with non-compatibility contexts. So I think that is something that needs to be fixed. It's possible that is the issue you are having. You could try setting `GraphicsProfile = ContextProfile.Compatibility`.
